### ISSUE TITLE
Fails to build on Android react-native 0.44

### ISSUE THREAD

**Issue by veikkaus5** [react-community/react-native-maps#1309]
Hi,

Has anyone got the project compiling successfully for Android with react-native version 0.44?

We receive the following error: 

/AirMapModule.java:25: error: cannot find symbol
import com.facebook.react.uimanager.UIBlock;

Yet, UIBlock seems to be available with RN 0.44. What could be the problem?

**Comment by Amurmurmur** [comment]
Strange error
Currently running RN 0.44 and RNM 0.15 with no problems so far.
Make sure you relink the package  and follow the installation guide for Android. 
```
react-native unlink react-native-maps
react-native link react-native-maps
```

**Comment by loiclouvet** [comment]
Same issue here

**Comment by veikkaus5** [comment]
We cannot get this working after a days worth of work. @Amurmurmur 's suggestion does not affect our issue. Current react-native-maps works just fine on iOS, but on android we just can't get it to build.

@Amurmurmur what react version are you running? We are using these with our application:

    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-maps": "^0.15.0",

 I'll attach the relevant error message we receive from gradlew: https://gist.github.com/veikkaus5/54ffe3b55f3f45f053e64a2f6d1f549a

As you can see the errors seem to point to a missing react-native as dependency or incompatibility with the new react-native 0.44.

**Comment by rtrann** [comment]
can you try:

cd android
gradlew clean
cd ..
react-native run-android

This often clears up build errors for me.

**Comment by veikkaus5** [comment]
@rtrann Thanks for the tip but we have done that several times.

The only way we got it working was adding react-native as a dependency in the react-native-maps package.json:

"react-native": "^0.44.0"

Does someone have an idea why this is necessary and does it introduce other issues?

**Comment by veikkaus5** [comment]
Actually that did not solve it either. I had run "npm install" manually in the react-native-maps and this caused the devDependencies to be installed. This then seemed to solve the build issue because now the symbols could be found. This is not a solution though as then you have two react instances at runtime.

So the problem remains, we cannot build this on Android.

**Comment by roz0n** [comment]
I too have been dealing with this issue for the better part of today and cannot seem to get it to work. I've attempted numerous solutions including the ones presented in this thread to no avail. I will attempt to build the app with iOS and report back.

**Comment by Pokute** [comment]
We found the problem and it seemed to be the missing repository declarations in correct build.gradle.

Adding them seemed to correct them. See https://github.com/veikkaus5/react-native-maps/commit/fcb679e47aaa398f14c595977cf8e5dc0def4a92

Without above, gradle will download React Native from maven repository. Too bad the version there is ancient (0.20.1) which results in above errors.

**Comment by madox2** [comment]
I have faced the same problem while using RN builded from source. I have solved this by substituting react-native with builded RN project. `android/build.gradle`:

```gradle
allprojects {
    // ...
    configure(project(':react-native-maps')) {
        resolutionStrategy {
            dependencySubstitution {
                substitute module('com.facebook.react:react-native') with project(':ReactAndroid')
            }
        }
    }
}
```
Or more generally substituting RN in each project:
```gradle
allprojects {
    // ...
    configurations.all {
        resolutionStrategy {
            dependencySubstitution {
                substitute module('com.facebook.react:react-native') with project(':ReactAndroid')
            }
        }
    }
}
```

**Comment by Palisand** [comment]
@madox2 Thank you. Your solution should be included in https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by subooom** [comment]
After doing what @madox2 said, I get a:

     Could not find method resolutionStrategy() for arguments  on project ':react-native-maps' of type org.gradle.api.Project.

What seems to be causing this?

**Comment by devotebest** [comment]
I got same error. any update?

**Comment by Corasonn** [comment]
I fixed the original problem with the help of [this](https://stackoverflow.com/questions/56951512/react-native-cannot-find-symbol-after-upgrade-to-0-60/56972260) comment:

build.gradle

```
allprojects {
    repositories {
        ...
        maven { url("$rootDir/../node_modules/react-native/android") }
    }
}


apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

Make sure react native is installed as dependency (as peer dependency the error will be still there in the project)

I had an error that node couldn't be found. If someone else also has it, [this](https://stackoverflow.com/a/69066155/4465464) helps.
