### ISSUE TITLE
'React/RCTView.h' file not found

### ISSUE THREAD

**Issue by Vetalyo** [react-community/react-native-maps#2013]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react: 16.2.0
react-native: 0.52.2
react-native-maps: 0.19.0
I'm using AppleMaps

### Steps to Reproduce

I've just install react-native-maps into my project by following Installation instructions. Without `react-native link` usage.

### Expected Behavior

Working maps.

### Actual Behavior

I get error in xcode: `'React/RCTView.h' file not found`.
By search in issues I find that I have to change:
```
AIRMap.h line 12
From #import <React/RCTComponent.h>
To #import "RCTComponent.h"

and

AIRMapCallout.h line 7
From #import "React/RCTView.h"
To #import "RCTView.h"
```
And all should be fine, but I get the next one error: `'React/RCTBorderStyle.h' file not found`.

**Comment by alvelig** [comment]
The problem is in your Podfile. Share a reproducible project please

**Comment by rborn** [comment]
It's possible that the issue is due to the `use_frameworks` flag.

Please read https://github.com/react-community/react-native-maps/issues/1923 and the linked bugs, and try to change the podfile as suggested and see if it works.

**Comment by Vetalyo** [comment]
@rborn As I can see almost all linked bugs about problems with pod installing when used `use_frameworks` flag. But in my case with that flag all installs complete:
```
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-maps` from `../node_modules/react-native-maps`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`
Downloading dependencies
Using FirebaseAnalytics (4.0.4)
Using FirebaseCore (4.0.8)
Using FirebaseInstanceID (2.0.0)
Using FirebaseMessaging (2.0.4)
Using GoogleToolboxForMac (2.1.3)
Using Protobuf (3.4.0)
Using React (0.52.2)
Using nanopb (0.3.8)
Using react-native-maps (0.19.0)
Using yoga (0.52.2.React)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 16 dependencies from the Podfile and 10 total pods installed.
```
Without `use_frameworks` flag get an error: 
`error: -fobjc-weak is not supported on the current deployment target`

**Comment by sabbyt54** [comment]
+1 Having the same issue as above

**Comment by kholiavko-roman** [comment]
@sabbyt54, did you found the solution ?

**Comment by sabbyt54** [comment]
@kholiavko-roman not yet

**Comment by helixbass** [comment]
@rborn @sabbyt54 having same issue, also have `use_frameworks!` uncommented in my `Podfile`. I'd already had to apply the workaround from #1923 (because I'd run into the transitive dependencies issue when trying to `pod install`) so that doesn't help fix the compilation errors

**Comment by rborn** [comment]
@Vetalyo can you put in place  a test project (on github) with the modules you are trying to use and a small readme on how to replicate the issue  so I can take a look? Thanks!

**Comment by sabbyt54** [comment]
I can confirm that if you start a fresh project, react-native-maps works, but once you include use_frameworks, runs into the issues stated above

**Comment by Vetalyo** [comment]
@rborn, as @sabbyt54 told, in new empty project `react-native-maps` - works. But it didn't in work in my podfile with `use_frameworks` flag.

**Comment by keeleycarrigan** [comment]
I rolled back to another point in my project where I was using RN Maps 0.18.3 and even though I had `use_frameworks` uncommented in that version of the Podfile everything worked. It's only when I upgraded to 0.19.0 that this became a problem.

**Comment by keeleycarrigan** [comment]
@helixbass thanks for pointing out that I might be mistaken. I went back to look at my project that was working even with `use_frameworks` uncommented. Since it was a few months ago that I installed `react-native-maps` I forgot that I actually used the "manual" installation method that was listed in that version's docs. It doesn't solve this particular problem, but I was able to start a project using a Podfile with `use_frameworks` (I'm using FBSDK, so I need it) and then install RN Maps manually. I hope this helps anyone needing to get past this issue while it's being solved properly.

1. Open your project in Xcode, right click on `Libraries` and click `Add
   Files to "Your Project Name"` Look under `node_modules/react-native-maps/lib/ios` and add `AIRMaps.xcodeproj`.
1. Add `libAIRMaps.a` to `Build Phases -> Link Binary With Libraries.
1. Click on `AIRMaps.xcodeproj` in `Libraries` and go the `Build
   Settings` tab. Double click the text to the right of `Header Search
   Paths` and verify that it has `$(SRCROOT)/../../react-native/React` as well as `$(SRCROOT)/../../react-native/Libraries/Image` - if they
   aren't, then add them. This is so Xcode is able to find the headers that
   the `AIRMaps` source files are referring to by pointing to the
   header files installed within the `react-native` `node_modules`
   directory.
1. Whenever you want to use it within React code now you can: `var MapView =
   require('react-native-maps');`

**Comment by rborn** [comment]
Closing, as the issue was `use_frameworks`  which for now it's not supported.

**Comment by rishiankush** [comment]
@rborn I am facing this issue in AIRMapCallout.h file

I can't delete use_frameworks as I am using charts as a dependency that uses swift.

Please see my pod file:
```
use_frameworks!

target 'DelGate' do
  pod 'SwiftyJSON', '3.1.4'      # 4.0.0
  pod 'Charts', '3.0.3'          # 3.1.1
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'    # 4.0
    end
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by rborn** [comment]
@rishiankush I don't really have a solution for when the `use_frameworks` case is needed 😔
Maybe you could find something about this on the cocoapods forums or find a way to install this module without cocoapods.

**Comment by rishiankush** [comment]
That means we still do not have support with swift for react native while using pods or using use_frameworks.

**Comment by rborn** [comment]
My iOS native knowledge is limited so I cannot answer this question

**Comment by keeleycarrigan** [comment]
@rishiankush the only option I know of right now is to use the method I posted above, but as I found out the other day it only works with `0.20.0` and possibly lower. I am stuck there as well since I'm using the FBSDK and Bolts needs `use_frameworks` uncommented. In my opinion this is kind of a big problem considering this is the suggested solution for maps and Facebook's own libraries conflict with it. One more reason I will be rebuilding our app natively in Swift after initial release so at least I only have to deal with RN on one platform.

**Comment by rishiankush** [comment]
@keeleycarrigan Please do not convert your files from objective-C one to swift as it will create a lot of problems and you have to delete your project and recreate it because react native works with objective-C conversion only. I am not good at IOS but I tried it.

the RCT bridge module only converts the code into objective-C but not into swift.

**Comment by keeleycarrigan** [comment]
@rishiankush I think you misunderstood my comment. I’m going to re-write my entire app in Swift. At that point I’m only going to be using this module for my Android version as my iOS app will be 100% native. I’m kind of tired of dealing with React Native in general so that will be my first step in moving away.

**Comment by rishiankush** [comment]
I just opened the issue here: https://github.com/react-community/react-native-maps/issues/2202

**Comment by olegserov** [comment]
Please see this solution that works without manual linking:
https://github.com/react-community/react-native-maps/issues/2324

**Comment by Balasnest** [comment]
Still facing this exact issue in Xcode 10. `use_framework` is commented also. Still showing **RCTView.h** file is not found.

Any workaround on this?

**Comment by rares-lupascu** [comment]
same here

**Comment by KingAmo** [comment]
```
   if target.name == "React"
      target.remove_from_project
    end
```
why you remove "React" ? is it possible the reason ?

**Comment by Meox92** [comment]
Same issue, but I think I fixed
**React version:** 
```
  "dependencies": {
    "@react-native-community/async-storage": "^1.5.1",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-maps": "0.25.0",
    "react-navigation": "^3.11.0"
  },
```

**Podfile:**
```
# platform :ios, '9.0'

target 'myProj' do
  use_frameworks!

   Pods for myProj
  pod 'Alamofire', '~> 5.0.0-beta.5'



  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'myProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```



React library is statically imported(project created with react-native init comand) so is not in podfile.


**How i fixed:**
1- Comment pod 'react-native-maps', :path => '../node_modules/react-native-maps' in podfile
2- In xCode open the project tab/Select your target(myProj in my case)/General/ Click "+" in Linked frameworks and libraries
3- Choose 'add another', add  AirMaps.xcodeproj from ../node_modules/react-native-maps/lib/ios/AirMaps.xcodeproj
4- Click "+" in Linked frameworks and libraries again
5- Choose libAirMaps.a

**Comment by Juanjo4U** [comment]
sudo rm -rf node_modules && yarn cache clean && yarn install && cd ios && pod deintegrate && pod install && cd ..

that always works for me, I set it on package.json inside scripts, for example:
"reinstall_force": "sudo rm -rf node_modules && yarn cache clean && yarn install && cd ios && pod deintegrate && pod install && cd ..",

then just on terminal run:  yarn reinstall_force

**Comment by Asadi123** [comment]
I am facing the same issue with 0.27.1 on react native 0.62.2. Is there any proper solution for it?

**Comment by NightWarrior** [comment]
> I am facing the same issue with 0.27.1 on react native 0.62.2. Is there any proper solution for it?

Anyone still having this issue, check your `ios/Podfile.lock` file and search for React, mine was being set to 0.11.0 for some reason while i was on 0.63.4 react native version. The issue causing that was in `package.json` file under `resolutions`, i deleted the followings and it fixed itself 

```
"@react-native-community/cli": "3.0.0-alpha.2",
"@react-native-community/cli-platform-android": "3.0.0-alpha.2",
"@react-native-community/cli-platform-ios": "3.0.0-alpha.2",
"@react-native-community/cli-tools": "2.8.3"
```
